version: "3"
services:
    gateway:
        build: .
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            NODE_ENV: development
            MONGO_URL: mongodb://mongo/DemoApp
        entrypoint: "node app"
    mongo:
        image: mongo
